version: '3'
services:
  web:
    container_name: drdeketelaereweb
    build:
      context: .
      dockerfile: Dockerfile

    pull_policy: build
    restart: unless-stopped
    expose:
      - "8001"
    ports:
      - 8001:80

networks:
  esnet: